server:
    port: 8080
spring:
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 운영서버
#    url: ENC(HBcLen39htQodFrLCYEh3s8xNxEVs5VEwYepq2y7oIAn6hz1yQmU0eZ1NCtqa+8EDZdJlQHix6rDMNawDCDiuNEs/3bwLZTEP6kroFdFkOcAStPDoVcaw6hRT8srZqIUPf/SBzNK5Cg=)
    # 개발서버
    url: ENC(gFAA7rKTjUQtYbBKiE5GQRP8fu6sGIIXrx7ZZS8Ec8eOAnDvwlWSgolXWBnGWcxA0u/4ALs0DVfkya2inQQWpYfN4sDzXjGf4F1XD2vhZC+WNqdOA72fROc/bwwg1Tf6nWXQ5qUU9n0=)
    username: ENC(bu13MVyW9tqJMQ6WhoxMDA==)
    password: ENC(wY1tCihwpyRiy3X1miTUnA==)
    hikari:
      leak-detection-threshold: 2000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      # 운영서버
#      host: company-source.com
      # 개발서버
      host : ENC(sRjA4p9Jt4qIuUMOdVVQqy7JCh223g/q/4rwRrPvszk=)
      port: 9000
      authentication-database: ENC(nhaDKWfag4QMbr8bFmCKqQ==)
      username: ENC(714l5ORmsn5+K+2ZjgrecA==)
      password: ENC(y7QgHOR0XwHMLkthu/eF2g==)
      database: ENC(3KwqupVoDR/3A/pHs9GrC62wBeW0jeEF)
  redis:
    # 운영서버
#    host: company-source.com
    # 개발서버
    host: k8b107.p.ssafy.io
    port: 8379
    password: ENC(/2hm83z+LAYJOoeAMzJ1zw==)
  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: ENC(pCWyshM94ml4zP8V/ywqkuFrEKDjyqLaBcQJzQ2eaH8=)
    # 발급받은 앱 비밀번호
    password: ENC(C2uaXBwMAQl4bcDEmNF0h/CXXhJuXVaTUtpZojj/4ok=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


jasypt:
  encryptor:
    bean: jasyptStringEncryptor


drinks :
  milkshake: ENC(3eNhgI3qWrTihqdQVAxFcCyvxSlVhqJ8SP7gCoCdsh/Cuzo6g7aD2wi+CUsvSd9IpcQuL42rMyCXGZekpAWLpg==)

cloud:
  aws:
    s3:
      bucket: pjbooklet
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ENC(8ECgvcPIlkC43HrpeitikNBLo0d9zWAJjyTHqZYPqFs=)
      secretKey: ENC(ntyBVOqbtQkHHmFKRxdsvdU2iLUV++BaOkE+G2q50yAizWl5zslW3S0L/10xMo73wvExMl6kol0=)

jwt:
  secretkey: ENC(i5CDcjY1mF90MCMwyoxHXEnvUmjNSVir)

notification:
  mattermost:
    enabled: true # mmSender를 사용할 지 여부, false면 알림이 오지 않는다
    webhook-url: ENC(ZK7M7+GPb/PQBswhz/YfyBEwp1B2akA5m7F4OfJw6WB3k26bxRajelLUZWg4r6neCKfsBNs8QPk6bidMMmYVZ1irVeoqM4KP)
    pretext: error message # attachments의 상단에 나오게 되는 일반 텍스트 문자


