server:
    port: 8080
spring:
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://company-source.com:8306/cs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: comso
    password: B107
#    url: jdbc:mysql://localhost:3306/cs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: bms1226@
    hikari:
      leak-detection-threshold: 2000
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      host: company-source.com
      authentication-database: admin
      username: comso
      password: B107
      database: company-source
      port: 9000
  #      mongodb://comso:B107@company-source.com:9000/?authMechanism=DEFAULT
  redis:
#    host: localhost # 3.38.106.18
#    port: 6379
#    password: "1234"

    host: company-source.com
    port: 6379
    password: "B107"