server:
    port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sourcecompany?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    hikari:
      leak-detection-threshold: 2000
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost # 3.38.106.18
    port: 6379
    password: 1234