version: '3'
services:
    backend_1:
        build: .
        container_name: backend
        ports:
            - "8080:8080"
        networks:
            - backend-network
        restart: always
    backend_2:
        build: .
        container_name: backend
        ports:
            - "8080:8080"
        networks:
            - backend-network
        restart: always
    backend_3:
        build: .
        container_name: backend
        ports:
            - "8080:8080"
        networks:
            - backend-network
        restart: always

networks:
  backend-network:
    driver: bridge