version: '3'
services:
    backend-1:
        build: .
        container_name: backend-1
        ports:
            - "8080:8080"
        networks:
            - backend-network
        restart: always
    backend-2:
        build: .
        container_name: backend-2
        ports:
            - "8081:8080"
        networks:
            - backend-network
        restart: always
    backend-3:
        build: .
        container_name: backend-3
        ports:
            - "8082:8080"
        networks:
            - backend-network
        restart: always

networks:
  backend-network:
    driver: bridge